<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN5mYJbf\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN5mYJbf/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerN5mYJbf.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerN5mYJbf\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerN5mYJbf\App_KernelProdContainer([
    'container.build_hash' => 'N5mYJbf',
    'container.build_id' => 'a00a0525',
    'container.build_time' => 1736493807,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN5mYJbf');
