<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_page1' => [[], ['_controller' => 'App\\Controller\\PageController::accueil'], [], [['text', '/accueil']], [], [], []],
    'app_page2' => [[], ['_controller' => 'App\\Controller\\PageController::présentation'], [], [['text', '/présentation']], [], [], []],
    'app_page3' => [[], ['_controller' => 'App\\Controller\\PageController::portfolio'], [], [['text', '/portfolio']], [], [], []],
    'app_page4' => [[], ['_controller' => 'App\\Controller\\PageController::contact'], [], [['text', '/contact']], [], [], []],
    'App\Controller\PageController::accueil' => [[], ['_controller' => 'App\\Controller\\PageController::accueil'], [], [['text', '/accueil']], [], [], []],
    'App\Controller\PageController::présentation' => [[], ['_controller' => 'App\\Controller\\PageController::présentation'], [], [['text', '/présentation']], [], [], []],
    'App\Controller\PageController::portfolio' => [[], ['_controller' => 'App\\Controller\\PageController::portfolio'], [], [['text', '/portfolio']], [], [], []],
    'App\Controller\PageController::contact' => [[], ['_controller' => 'App\\Controller\\PageController::contact'], [], [['text', '/contact']], [], [], []],
];
