<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMOdrnxn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMOdrnxn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMOdrnxn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMOdrnxn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMOdrnxn\App_KernelDevDebugContainer([
    'container.build_hash' => 'MOdrnxn',
    'container.build_id' => 'aaff90fc',
    'container.build_time' => 1736408715,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMOdrnxn');
